@echo off
setlocal EnableDelayedExpansion

rem Imports RSPSi map exports (m[x]_[z].dat / l[x]_[z].dat) into the maps module,
rem repacks the caches and clears the local client cache. See content\other\maps\README.md.

set "EXPORTS=C:\Users\andre\Desktop\map-exports"
set "CLIENT_CACHE=C:\Users\andre\.rsmod-client\cache"
set "REPO=%~dp0"
set "MAPS_MODULE=%REPO%content\other\maps"
set "MAP_RES=%MAPS_MODULE%\src\main\resources\map"
set "MAP_SRC=%MAPS_MODULE%\src\main\kotlin\org\rsmod\content\other\maps"

if not exist "%EXPORTS%" (
    echo Export folder not found: %EXPORTS%
    goto :fail
)
if not exist "%MAP_RES%" mkdir "%MAP_RES%"

set COPIED=0
set MISSING=

echo == Copying exports from %EXPORTS%
for %%F in ("%EXPORTS%\m*_*.dat" "%EXPORTS%\l*_*.dat") do (
    set "NAME=%%~nF"
    copy /Y "%%~fF" "%MAP_RES%\!NAME!" >nul
    if errorlevel 1 (
        echo   FAILED  %%~nxF
        goto :fail
    )
    echo   %%~nxF  -^>  map\!NAME!
    set /a COPIED+=1

    rem Square key is the name without the leading m/l, e.g. 48_54.
    set "SQUARE=!NAME:~1!"
    findstr /S /L /C:"/map/!NAME!\"" "%MAP_SRC%\*.kt" >nul 2>&1
    if errorlevel 1 (
        echo   WARNING: no builder registers /map/!NAME!
        echo !MISSING! | findstr /C:" !SQUARE! " >nul || set "MISSING=!MISSING! !SQUARE! "
    )
)

if %COPIED%==0 (
    echo No m*_*.dat / l*_*.dat files found in %EXPORTS%
    goto :fail
)
echo Copied %COPIED% file(s).

if defined MISSING (
    echo.
    echo The following squares were exported but have no builder class, so they will
    echo NOT be packed:%MISSING%
    choice /C YN /M "Create MapTileBuilder/MapLocSpawnBuilder classes for them now"
    if errorlevel 2 (
        echo Skipping. Add resourceFile lines to a builder yourself before packing.
    ) else (
        for %%S in (%MISSING%) do call :create_builders %%S
    )
)

echo.
echo == Running gradlew install
pushd "%REPO%"
call gradlew.bat install --console=plain
set "RC=%ERRORLEVEL%"
popd
if not "%RC%"=="0" (
    echo gradlew install failed ^(exit %RC%^). Client cache left untouched.
    goto :fail
)

echo.
echo == Deleting client cache %CLIENT_CACHE%
if exist "%CLIENT_CACHE%" (
    rmdir /S /Q "%CLIENT_CACHE%"
) else (
    echo   ^(not present, nothing to delete^)
)

echo.
echo Done. Start the server and client.
pause
exit /b 0

:fail
echo.
echo Import aborted.
pause
exit /b 1

rem ---------------------------------------------------------------------------
rem :create_builders <x_z>  - writes Square<x_z>Tiles.kt and Square<x_z>Locs.kt
rem registering /map/m<x_z> and /map/l<x_z>.
rem ---------------------------------------------------------------------------
:create_builders
set "SQ=%~1"
set "TILES=%MAP_SRC%\Square%SQ%Tiles.kt"
set "LOCS=%MAP_SRC%\Square%SQ%Locs.kt"

if exist "%TILES%" (
    echo   %TILES% already exists, not overwriting.
) else (
    > "%TILES%" (
        echo package org.rsmod.content.other.maps
        echo.
        echo import org.rsmod.api.type.builders.map.tile.MapTileBuilder
        echo.
        echo /** Custom terrain ^(`m%SQ%`^) generated by import-map.bat. See this module's README. */
        echo object Square%SQ%Tiles : MapTileBuilder^(^) {
        echo     override fun onPackMapTask^(^) {
        echo         resourceFile^<Square%SQ%Tiles^>^("/map/m%SQ%"^)
        echo     }
        echo }
    )
    echo   Created %TILES%
)

if exist "%LOCS%" (
    echo   %LOCS% already exists, not overwriting.
) else (
    > "%LOCS%" (
        echo package org.rsmod.content.other.maps
        echo.
        echo import org.rsmod.api.type.builders.map.loc.MapLocSpawnBuilder
        echo.
        echo /** Custom loc placements ^(`l%SQ%`^) generated by import-map.bat. See this module's README. */
        echo object Square%SQ%Locs : MapLocSpawnBuilder^(^) {
        echo     override fun onPackMapTask^(^) {
        echo         resourceFile^<Square%SQ%Locs^>^("/map/l%SQ%"^)
        echo     }
        echo }
    )
    echo   Created %LOCS%
)

if not exist "%MAP_RES%\m%SQ%" echo   NOTE: map\m%SQ% is missing - packCache will fail until you export it too.
if not exist "%MAP_RES%\l%SQ%" echo   NOTE: map\l%SQ% is missing - packCache will fail until you export it too.
exit /b 0
